// pybind11 bindings for pyamg's threaded sparse BLAS kernels.
// Hand-written (not generated by bindthem.py) so we can release the GIL
// across OpenMP regions and bind both CSR and BSR variants explicitly.

#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <pybind11/complex.h>

#ifdef _OPENMP
#include <omp.h>
#endif

#include "spmv.h"
#include "spgemm.h"
#include "rap.h"

namespace py = pybind11;
using pyamg::sparse_blas::csr_matvec;
using pyamg::sparse_blas::bsr_matvec;
using pyamg::sparse_blas::csr_matmat_pass1;
using pyamg::sparse_blas::csr_matmat_pass2;
using pyamg::sparse_blas::rap_pass1;
using pyamg::sparse_blas::rap_pass2;

// ---- thread-control ----

static void set_num_threads(int n) {
#ifdef _OPENMP
    if (n < 1) n = 1;
    omp_set_num_threads(n);
#else
    (void)n;
#endif
}

static int get_num_threads() {
#ifdef _OPENMP
    return omp_get_max_threads();
#else
    return 1;
#endif
}

static int has_openmp() {
#ifdef _OPENMP
    return 1;
#else
    return 0;
#endif
}

// ---- CSR SpMV ----

template <class I, class T>
static void _csr_matvec(py::array_t<I, py::array::c_style | py::array::forcecast> Ap,
                        py::array_t<I, py::array::c_style | py::array::forcecast> Aj,
                        py::array_t<T, py::array::c_style | py::array::forcecast> Ax,
                        py::array_t<T, py::array::c_style | py::array::forcecast> x,
                        py::array_t<T, py::array::c_style> y)
{
    auto bAp = Ap.template unchecked<1>();
    auto bAj = Aj.template unchecked<1>();
    auto bAx = Ax.template unchecked<1>();
    auto bx  = x.template unchecked<1>();
    auto by  = y.template mutable_unchecked<1>();

    const I n_row = static_cast<I>(bAp.shape(0) - 1);

    py::gil_scoped_release release;
    csr_matvec<I, T>(n_row, bAp.data(0), bAj.data(0), bAx.data(0), bx.data(0),
                     by.mutable_data(0));
}

// ---- BSR SpMV ----

template <class I, class T>
static void _bsr_matvec(I R_blk,
                        I C_blk,
                        py::array_t<I, py::array::c_style | py::array::forcecast> Ap,
                        py::array_t<I, py::array::c_style | py::array::forcecast> Aj,
                        py::array_t<T, py::array::c_style | py::array::forcecast> Ax,
                        py::array_t<T, py::array::c_style | py::array::forcecast> x,
                        py::array_t<T, py::array::c_style> y)
{
    auto bAp = Ap.template unchecked<1>();
    auto bAj = Aj.template unchecked<1>();
    auto bx  = x.template unchecked<1>();
    auto by  = y.template mutable_unchecked<1>();

    const I n_brow = static_cast<I>(bAp.shape(0) - 1);

    // Ax is stored as a 1-D buffer of length n_blocks*R_blk*C_blk (forcecast
    // flattens any 3-D BSR data view we receive from scipy).
    auto bAx = Ax.template unchecked<1>();

    py::gil_scoped_release release;
    bsr_matvec<I, T>(n_brow, R_blk, C_blk,
                     bAp.data(0), bAj.data(0), bAx.data(0),
                     bx.data(0), by.mutable_data(0));
}

// ---- CSR SpGEMM, two-pass ----

template <class I>
static void _csr_matmat_pass1(I n_col,
                              py::array_t<I, py::array::c_style | py::array::forcecast> Ap,
                              py::array_t<I, py::array::c_style | py::array::forcecast> Aj,
                              py::array_t<I, py::array::c_style | py::array::forcecast> Bp,
                              py::array_t<I, py::array::c_style | py::array::forcecast> Bj,
                              py::array_t<I, py::array::c_style> Cp)
{
    auto bAp = Ap.template unchecked<1>();
    auto bAj = Aj.template unchecked<1>();
    auto bBp = Bp.template unchecked<1>();
    auto bBj = Bj.template unchecked<1>();
    auto bCp = Cp.template mutable_unchecked<1>();

    const I n_row = static_cast<I>(bAp.shape(0) - 1);

    py::gil_scoped_release release;
    csr_matmat_pass1<I>(n_row, n_col,
                        bAp.data(0), bAj.data(0),
                        bBp.data(0), bBj.data(0),
                        bCp.mutable_data(0));
}

template <class I, class T>
static void _csr_matmat_pass2(I n_col,
                              py::array_t<I, py::array::c_style | py::array::forcecast> Ap,
                              py::array_t<I, py::array::c_style | py::array::forcecast> Aj,
                              py::array_t<T, py::array::c_style | py::array::forcecast> Ax,
                              py::array_t<I, py::array::c_style | py::array::forcecast> Bp,
                              py::array_t<I, py::array::c_style | py::array::forcecast> Bj,
                              py::array_t<T, py::array::c_style | py::array::forcecast> Bx,
                              py::array_t<I, py::array::c_style | py::array::forcecast> Cp,
                              py::array_t<I, py::array::c_style> Cj,
                              py::array_t<T, py::array::c_style> Cx,
                              bool sort_indices)
{
    auto bAp = Ap.template unchecked<1>();
    auto bAj = Aj.template unchecked<1>();
    auto bAx = Ax.template unchecked<1>();
    auto bBp = Bp.template unchecked<1>();
    auto bBj = Bj.template unchecked<1>();
    auto bBx = Bx.template unchecked<1>();
    auto bCp = Cp.template unchecked<1>();
    auto bCj = Cj.template mutable_unchecked<1>();
    auto bCx = Cx.template mutable_unchecked<1>();

    const I n_row = static_cast<I>(bAp.shape(0) - 1);

    py::gil_scoped_release release;
    csr_matmat_pass2<I, T>(n_row, n_col,
                           bAp.data(0), bAj.data(0), bAx.data(0),
                           bBp.data(0), bBj.data(0), bBx.data(0),
                           bCp.data(0),
                           bCj.mutable_data(0), bCx.mutable_data(0),
                           sort_indices);
}

// ---- fused RAP, two-pass ----

template <class I>
static void _rap_pass1(I n_inner, I n_col,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Rp,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Rj,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Ap,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Aj,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Pp,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Pj,
                       py::array_t<I, py::array::c_style> Cp)
{
    auto bRp = Rp.template unchecked<1>();
    auto bRj = Rj.template unchecked<1>();
    auto bAp = Ap.template unchecked<1>();
    auto bAj = Aj.template unchecked<1>();
    auto bPp = Pp.template unchecked<1>();
    auto bPj = Pj.template unchecked<1>();
    auto bCp = Cp.template mutable_unchecked<1>();

    const I n_row = static_cast<I>(bRp.shape(0) - 1);

    py::gil_scoped_release release;
    rap_pass1<I>(n_row, n_inner, n_col,
                 bRp.data(0), bRj.data(0),
                 bAp.data(0), bAj.data(0),
                 bPp.data(0), bPj.data(0),
                 bCp.mutable_data(0));
}

template <class I, class T>
static void _rap_pass2(int block_size, I n_inner, I n_col,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Rp,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Rj,
                       py::array_t<T, py::array::c_style | py::array::forcecast> Rx,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Ap,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Aj,
                       py::array_t<T, py::array::c_style | py::array::forcecast> Ax,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Pp,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Pj,
                       py::array_t<T, py::array::c_style | py::array::forcecast> Px,
                       py::array_t<I, py::array::c_style | py::array::forcecast> Cp,
                       py::array_t<I, py::array::c_style> Cj,
                       py::array_t<T, py::array::c_style> Cx,
                       bool sort_indices)
{
    auto bRp = Rp.template unchecked<1>();
    auto bRj = Rj.template unchecked<1>();
    auto bRx = Rx.template unchecked<1>();
    auto bAp = Ap.template unchecked<1>();
    auto bAj = Aj.template unchecked<1>();
    auto bAx = Ax.template unchecked<1>();
    auto bPp = Pp.template unchecked<1>();
    auto bPj = Pj.template unchecked<1>();
    auto bPx = Px.template unchecked<1>();
    auto bCp = Cp.template unchecked<1>();
    auto bCj = Cj.template mutable_unchecked<1>();
    auto bCx = Cx.template mutable_unchecked<1>();

    const I n_row = static_cast<I>(bRp.shape(0) - 1);

    py::gil_scoped_release release;
    rap_pass2<I, T>(block_size, n_row, n_inner, n_col,
                    bRp.data(0), bRj.data(0), bRx.data(0),
                    bAp.data(0), bAj.data(0), bAx.data(0),
                    bPp.data(0), bPj.data(0), bPx.data(0),
                    bCp.data(0),
                    bCj.mutable_data(0), bCx.mutable_data(0),
                    sort_indices);
}

PYBIND11_MODULE(sparse_blas, m) {
    m.doc() = "pyamg threaded sparse BLAS kernels (SpMV, SpGEMM, fused RAP).";

    m.def("set_num_threads", &set_num_threads,
          "Set OpenMP thread count for pyamg sparse BLAS kernels.",
          py::arg("n"));
    m.def("get_num_threads", &get_num_threads,
          "Return current OpenMP thread count (1 if OpenMP unavailable).");
    m.def("has_openmp", &has_openmp,
          "Return 1 if compiled with OpenMP support, else 0.");

    // CSR matvec: instantiate for the four (index, value) types pyamg uses.
    m.def("csr_matvec", &_csr_matvec<int, float>);
    m.def("csr_matvec", &_csr_matvec<int, double>);
    m.def("csr_matvec", &_csr_matvec<int, std::complex<float>>);
    m.def("csr_matvec", &_csr_matvec<int, std::complex<double>>);

    // BSR matvec: same instantiations.
    m.def("bsr_matvec", &_bsr_matvec<int, float>);
    m.def("bsr_matvec", &_bsr_matvec<int, double>);
    m.def("bsr_matvec", &_bsr_matvec<int, std::complex<float>>);
    m.def("bsr_matvec", &_bsr_matvec<int, std::complex<double>>);

    // CSR SpGEMM (CSR @ CSR -> CSR), two-pass.
    m.def("csr_matmat_pass1", &_csr_matmat_pass1<int>);
    m.def("csr_matmat_pass2", &_csr_matmat_pass2<int, float>,
          py::arg("n_col"), py::arg("Ap"), py::arg("Aj"), py::arg("Ax"),
          py::arg("Bp"), py::arg("Bj"), py::arg("Bx"),
          py::arg("Cp"), py::arg("Cj"), py::arg("Cx"),
          py::arg("sort_indices") = true);
    m.def("csr_matmat_pass2", &_csr_matmat_pass2<int, double>,
          py::arg("n_col"), py::arg("Ap"), py::arg("Aj"), py::arg("Ax"),
          py::arg("Bp"), py::arg("Bj"), py::arg("Bx"),
          py::arg("Cp"), py::arg("Cj"), py::arg("Cx"),
          py::arg("sort_indices") = true);
    m.def("csr_matmat_pass2", &_csr_matmat_pass2<int, std::complex<float>>,
          py::arg("n_col"), py::arg("Ap"), py::arg("Aj"), py::arg("Ax"),
          py::arg("Bp"), py::arg("Bj"), py::arg("Bx"),
          py::arg("Cp"), py::arg("Cj"), py::arg("Cx"),
          py::arg("sort_indices") = true);
    m.def("csr_matmat_pass2", &_csr_matmat_pass2<int, std::complex<double>>,
          py::arg("n_col"), py::arg("Ap"), py::arg("Aj"), py::arg("Ax"),
          py::arg("Bp"), py::arg("Bj"), py::arg("Bx"),
          py::arg("Cp"), py::arg("Cj"), py::arg("Cx"),
          py::arg("sort_indices") = true);

    // Fused triple-product RAP, two-pass. Symbolic pass operates on
    // (block-)indices only and is shared between CSR and BSR. Numeric
    // pass takes block_size: 1 (CSR), or BSR block size; specialized
    // unrolled kernels exist for {1, 2, 3, 4, 6, 8}, runtime fallback
    // otherwise.
    m.def("rap_pass1", &_rap_pass1<int>);
    m.def("rap_pass2", &_rap_pass2<int, float>,
          py::arg("block_size"), py::arg("n_inner"), py::arg("n_col"),
          py::arg("Rp"), py::arg("Rj"), py::arg("Rx"),
          py::arg("Ap"), py::arg("Aj"), py::arg("Ax"),
          py::arg("Pp"), py::arg("Pj"), py::arg("Px"),
          py::arg("Cp"), py::arg("Cj"), py::arg("Cx"),
          py::arg("sort_indices") = true);
    m.def("rap_pass2", &_rap_pass2<int, double>,
          py::arg("block_size"), py::arg("n_inner"), py::arg("n_col"),
          py::arg("Rp"), py::arg("Rj"), py::arg("Rx"),
          py::arg("Ap"), py::arg("Aj"), py::arg("Ax"),
          py::arg("Pp"), py::arg("Pj"), py::arg("Px"),
          py::arg("Cp"), py::arg("Cj"), py::arg("Cx"),
          py::arg("sort_indices") = true);
    m.def("rap_pass2", &_rap_pass2<int, std::complex<float>>,
          py::arg("block_size"), py::arg("n_inner"), py::arg("n_col"),
          py::arg("Rp"), py::arg("Rj"), py::arg("Rx"),
          py::arg("Ap"), py::arg("Aj"), py::arg("Ax"),
          py::arg("Pp"), py::arg("Pj"), py::arg("Px"),
          py::arg("Cp"), py::arg("Cj"), py::arg("Cx"),
          py::arg("sort_indices") = true);
    m.def("rap_pass2", &_rap_pass2<int, std::complex<double>>,
          py::arg("block_size"), py::arg("n_inner"), py::arg("n_col"),
          py::arg("Rp"), py::arg("Rj"), py::arg("Rx"),
          py::arg("Ap"), py::arg("Aj"), py::arg("Ax"),
          py::arg("Pp"), py::arg("Pj"), py::arg("Px"),
          py::arg("Cp"), py::arg("Cj"), py::arg("Cx"),
          py::arg("sort_indices") = true);
}
